### ISSUE TITLE
Memory error with Reuters and  models.reg_lstm

### ISSUE THREAD

**Issue by PiercarloSlavazza** [castorini/hedwig#39]
# Env

* Ubuntu 18.04.3 (Digital Ocean)
* 32 GB RAM
* no GPU
* Everything installed as per the Readme

# Memory Error

Command executed:

```bash
python -m models.reg_lstm --dataset Reuters --mode static --batch-size 32 --lr 0.01 --epochs 30 --bidirectional --num-layers 1 --hidden-dim 512 --wdrop 0.1 --embed-droprate 0.2 --dropout 0.5 --beta-ema 0.99 --seed 3435
```

It reaches 100% in the progress bar, and then gives "Memory error" as follows:

```
(castor) root@hedwig:~/hedwig# python -m models.reg_lstm --dataset Reuters --mode rand --batch-size 32 --lr 0.01 --epochs 10 --bidirectional --num-layers 1 --hidden-dim 512 --wdrop 0.1 --embed-droprate 0.2 --dropout 0.5 --beta-ema 0.99 --seed 3435
  0%|                                                                                                 | 0/3000001 [00:00<?, ?it/s]Skipping token 3000000 with 1-dimensional vector ['300']; likely a header
100%|█████████████████████████████████████████████████████████████████████████████████| 3000001/3000001 [05:06<00:00, 9782.60it/s]
Traceback (most recent call last):
  File "/root/anaconda3/envs/castor/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/anaconda3/envs/castor/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/hedwig/models/reg_lstm/__main__.py", line 95, in <module>
    unk_init=UnknownWordVecCache.unk)
  File "/root/hedwig/datasets/reuters.py", line 92, in iters
    vectors = Vectors(name=vectors_name, cache=vectors_cache, unk_init=unk_init)
  File "/root/anaconda3/envs/castor/lib/python3.6/site-packages/torchtext/vocab.py", line 236, in __init__
    self.cache(name, cache, url=url)
  File "/root/anaconda3/envs/castor/lib/python3.6/site-packages/torchtext/vocab.py", line 327, in cache
    self.vectors = torch.Tensor(vectors).view(-1, dim)
MemoryError
```

Are 32GB RAM really not enough for this task? If so, do you have an idea of the minimum RAM requirements?

Note: before getting the memory error, I was getting _another_ error, explained and solved (?) as follows:

*TypeError: __init__() got an unexpected keyword argument 'dtype'*

Error log:

```
(castor) root@hedwig:~/hedwig# python -m models.reg_lstm --dataset Reuters --mode rand --batch-size 32 --lr 0.01 --epochs 10 --bidirectional --num-layers 1 --hidden-dim 512 --wdrop 0.1 --embed-droprate 0.2 --dropout 0.5 --beta-ema 0.99 --seed 3435
Traceback (most recent call last):
  File "/root/anaconda3/envs/castor/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/anaconda3/envs/castor/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/hedwig/models/reg_lstm/__main__.py", line 11, in <module>
    from datasets.aapd import AAPD
  File "/root/hedwig/datasets/aapd.py", line 9, in <module>
    from datasets.reuters import clean_string, split_sents
  File "/root/hedwig/datasets/reuters.py", line 126, in <module>
    class ReutersTFIDF(Reuters):
  File "/root/hedwig/datasets/reuters.py", line 128, in ReutersTFIDF
    TEXT_FIELD = Field(sequential=False, use_vocab=False, batch_first=True, preprocessing=load_json, dtype=torch.float)
TypeError: __init__() got an unexpected keyword argument 'dtype'
```

I have just removed the `dtype` parameter - no idea whether this might be the cause of the above memory error - or is anyway harming the training.

**Comment by PiercarloSlavazza** [comment]
With 52GB RAM I was able to successfully overcome this issue - please, add a requirements section to your readme.

**Comment by DecentMakeover** [comment]
facing a similar issue is there a workaround for this to be able to run this on 32 GB RAM?
